#!/usr/bin/python2.7

import time
import sys
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(7, GPIO.OUT)

char = sys.argv[1]

def light(led):
        if led == 'left_above':
                GPIO.output(16, 1)
        elif led == 'left_below':
                GPIO.output(13, 1)
        elif led == 'middle_above':
                GPIO.output(18, 1)
        elif led == 'middle_middle':
                GPIO.output(15, 1)
        elif led == 'middle_below':
                GPIO.output(12, 1)
        elif led == 'right_above':
                GPIO.output(22, 1)
        elif led == 'right_below':
                GPIO.output(11, 1)
        elif led == 'reset':
                GPIO.output(11, 0)
                GPIO.output(12, 0)
                GPIO.output(13, 0)
                GPIO.output(15, 0)
                GPIO.output(16, 0)
                GPIO.output(18, 0)
                GPIO.output(22, 0)
                GPIO.output(7, 0)       


if char == 'reset':
        light('reset')
elif char == '.':
        light('dot')
#Captital letters
elif char == 'A':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'B':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'C':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_below')
elif char == 'D':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'E':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
elif char == 'F':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
elif char == 'G':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_below')
        light('right_below')
elif char == 'H':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'I':
        light('reset')
        light('left_above')
        light('left_below')
elif char == 'J':
        light('reset')
        light('middle_above')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'K':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'L':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_below')
elif char == 'M':
        light('reset')
        light('left_below')
        light('middle_above')
        light('right_below')
elif char == 'N':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('right_above')
        light('right_below')
elif char == 'O':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'P':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('right_above')
elif char == 'Q':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'R':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'S':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == 'T':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
elif char == 'U':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'V':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'W':
        light('reset')
        light('left_above')
        light('middle_below')
        light('right_above')
elif char == 'X':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'Y':
        light('reset')
        light('left_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'Z':
        light('reset')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
#Minor letters
elif char == 'a':
        light('reset')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'b':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == 'c':
        light('reset')
        light('left_below')
        light('middle_middle')
        light('middle_below')
elif char == 'd':
        light('reset')
        light('left_below')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'e':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
elif char == 'f':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
elif char == 'g':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'h':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_below')
elif char == 'i':
        light('reset')
        light('left_below')
elif char == 'j':
        light('reset')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'k':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_below')
elif char == 'l':
        light('reset')
        light('left_above')
        light('left_below')
elif char == 'm':
        light('reset')
        light('left_below')
        light('middle_middle')
        light('right_below')
elif char == 'n':
        light('reset')
        light('left_below')
        light('middle_middle')
        light('right_below')
elif char == 'o':
        light('reset')
        light('left_below')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == 'p':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('right_above')
elif char == 'q':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'r':
        light('reset')
        light('left_below')
        light('middle_middle')
elif char == 's':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == 't':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
elif char == 'u':
        light('reset')
        light('left_below')
        light('middle_below')
        light('right_below')
elif char == 'v':
        light('reset')
        light('left_below')
        light('middle_below')
        light('right_below')
elif char == 'w':
        light('reset')
        light('left_below')
        light('middle_below')
        light('right_below')
elif char == 'x':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == 'y':
        light('reset')
        light('left_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == 'z':
        light('reset')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
#Numbers
elif char == '0':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == '1':
        light('reset')
        light('left_above')
        light('left_below')
elif char == '2':
        light('reset')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
elif char == '3':
        light('reset')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == '4':
        light('reset')
        light('left_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
elif char == '5':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == '6':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_below')
elif char == '7':
        light('reset')
        light('middle_above')
        light('right_above')
        light('right_below')
elif char == '8':
        light('reset')
        light('left_above')
        light('left_below')
        light('middle_above')
        light('middle_middle')
        light('middle_below')
        light('right_above')
        light('right_below')
elif char == '9':
        light('reset')
        light('left_above')
        light('middle_above')
        light('middle_middle')
        light('right_above')
        light('right_below')
